Repository cloudforet-io/plugin-azure-inven-collector, pull requests merged in 2022-12, with the labels that each got.

#34 Add blob count and size info for StorageAccounts
  src/spaceone/inventory/connector/monitor/connector.py
  src/spaceone/inventory/libs/manager.py
  src/spaceone/inventory/model/storage_accounts/cloud_service.py
  src/spaceone/inventory/model/storage_accounts/cloud_service_type.py
  src/spaceone/inventory/model/storage_accounts/data.py
  src/spaceone/inventory/model/storage_accounts/widget/storage_accounts_blob_count_by_account.yaml
  src/spaceone/inventory/model/storage_accounts/widget/storage_accounts_blob_count_by_region.yaml
  src/spaceone/inventory/model/storage_accounts/widget/storage_accounts_blob_size_by_account.yaml
  src/spaceone/inventory/model/storage_accounts/widget/storage_accounts_blob_size_by_resource_group.yaml
  src/spaceone/inventory/model/storage_accounts/widget/storage_accounts_count_by_resource_group.yaml
  src/spaceone/inventory/model/storage_accounts/widget/storage_accounts_total_blob_count.yaml
  src/spaceone/inventory/model/storage_accounts/widget/storage_accounts_total_blob_size.yaml
Labels: enhancement

#35 Modify StorageAccounts's manager.py
  src/spaceone/inventory/manager/load_balancers/instance_manager.py
  src/spaceone/inventory/manager/storage_accounts/instance_manager.py
  src/spaceone/inventory/model/storage_accounts/cloud_service_type.py
Labels: bug, enhancement

#37 Modify container_item info in StorageAccounts data
  src/spaceone/inventory/model/storage_accounts/cloud_service.py
  src/spaceone/inventory/model/storage_accounts/data.py
Labels: enhancement

#38 Modify default current time
  src/spaceone/inventory/manager/storage_accounts/instance_manager.py
Labels: enhancement

#39 docs: update README.md for v1.6.1
  README.md
  src/spaceone/inventory/model/storage_accounts/widget/storage_accounts_blob_size_by_resource_group.yaml
Labels: documentation

#42 add options to dynamically receive ASSET_URL
  README.md
  src/spaceone/inventory/conf/cloud_service_conf.py
  src/spaceone/inventory/libs/manager.py
  src/spaceone/inventory/model/application_gateways/cloud_service_type.py
  src/spaceone/inventory/model/container_instances/cloud_service_type.py
  src/spaceone/inventory/model/cosmos_db/cloud_service_type.py
  src/spaceone/inventory/model/disks/cloud_service_type.py
  src/spaceone/inventory/model/key_vaults/cloud_service_type.py
  src/spaceone/inventory/model/load_balancers/cloud_service_type.py
  src/spaceone/inventory/model/mysql_servers/cloud_service_type.py
  src/spaceone/inventory/model/nat_gateways/cloud_service_type.py
  src/spaceone/inventory/model/network_security_groups/cloud_service_type.py
  src/spaceone/inventory/model/postgresql_servers/cloud_service_type.py
  src/spaceone/inventory/model/public_ip_addresses/cloud_service_type.py
  src/spaceone/inventory/model/snapshots/cloud_service_type.py
  src/spaceone/inventory/model/sql_databases/cloud_service_type.py
  src/spaceone/inventory/model/sql_servers/cloud_service_type.py
  src/spaceone/inventory/model/storage_accounts/cloud_service_type.py
  src/spaceone/inventory/model/virtual_machines/cloud_service_type.py
  src/spaceone/inventory/model/virtual_networks/cloud_service_type.py
  src/spaceone/inventory/model/vm_scale_sets/cloud_service_type.py
  src/spaceone/inventory/model/web_pubsub_service/cloud_service_type.py
  test/api/test_cloud_service_api.py
Labels: documentation, enhancement
